booking/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='booking'



urlpatterns = [
    path('BookingOnline' , views.BookingOnline , name='BookingOnline'),
    path('BookingOnline/outpatient_schedule' , views.outpatient_schedule , name='outpatient_schedule'),
]

inquiries_complaints/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='inquiries_complaints'

urlpatterns = [
    # path('add_to_cart' , views.add_to_cart , name='add_to_cart'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('settings.urls' ,namespace='settings')),
    path('',include('booking.urls' ,namespace='booking')),
    # path('',include('settings.urls' ,namespace='settings')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='settings'


urlpatterns = [
    path('' , views.home , name='home'),
]

booking/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.


class Clinics(models.Model):
    name=models.CharField(max_length=60)
    available=models.BooleanField(default=False,verbose_name='Available For Outpatient')

    class Meta:
        verbose_name = _("clinics")
        verbose_name_plural = _("clinics")

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse("clinics_detail", kwargs={"pk": self.pk})


class Booking(models.Model):
    clinics=models.ForeignKey(Clinics,on_delete=models.CASCADE)
    username=models.CharField(max_length=50)
    phonenumber=models.CharField(max_length=50)
    email=models.EmailField()
    description=models.CharField(max_length=500)
    
    
    
    
    class Meta:
        verbose_name = _("booking")
        verbose_name_plural = _("bookings")

    def __str__(self):
        return self.username + ' ==> ' + str(self.clinics) + ' ==> ' + self.phonenumber

    # def get_absolute_url(self):
    #     return reverse("booking_detail", kwargs={"pk": self.pk})

class WorkDay(models.Model):
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name

class Outpatient_schedule(models.Model):
    clinics=models.ForeignKey(Clinics,on_delete=models.CASCADE,limit_choices_to={'available': True})
    floor=models.CharField(max_length=30)
    workdays=models.ManyToManyField(WorkDay, blank=True, related_name='work_days')

    class Meta:
        verbose_name = _("Outpatient_schedule")
        verbose_name_plural = _("Outpatient_schedules")

    # def get_absolute_url(self):
    #     return reverse("Outpatient_schedule_detail", kwargs={"pk": self.pk})

inquiries_complaints/models.py
from django.db import models

# Create your models here.
from django.utils.translation import gettext_lazy as _

class inquiries(models.Model):
    username=models.CharField(max_length=50)
    phonenumber=models.CharField(max_length=20,verbose_name=_("phonenumber"))
    message=models.CharField(max_length=1000)


    class Meta:
        verbose_name = _("inquiries")
        verbose_name_plural = _("inquiriss")

    def __str__(self):
        return 'name : ' + self.username + ' <== phonenumber ==> ' + self.phonenumber

    # def get_absolute_url(self):
    #     return reverse("inquiries_detail", kwargs={"pk": self.pk})

settings/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.

class settings(models.Model):
    logo=models.ImageField(upload_to='logo/')
    phoennumbers=models.CharField(max_length=100)
    adress=models.CharField(max_length=150)
    fb_url=models.URLField()
    tw_url=models.URLField()

    class Meta:
        verbose_name = _("settings")
        verbose_name_plural = _("settings")

    # def __str__(self):
    #     return self.site_name

    # def get_absolute_url(self):
    #     return reverse("settings_detail", kwargs={"pk": self.pk})

booking/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
# Create your views here.
from.models import Booking,Clinics,Outpatient_schedule


def BookingOnline(request):
    all_clinics=Clinics.objects.all()
    if request.method=='POST':
        clinic_id = request.POST['clinic']
        # clinic=request.POST['clinic']
        name=request.POST['name']
        phone=request.POST['phone']
        email=request.POST['email']
        message=request.POST['message']
        clinic = Clinics.objects.get(pk=clinic_id)
        submit=Booking(
            clinics=clinic,
            username=name,
            phonenumber=phone,
            email=email,
            description=message,
        )
        submit.save()
        messages.success(request, 'Information send successfully')
        return redirect('/')
    context={'all_clinics':all_clinics}
    return render(request,'booking/regiter.html',context)



def outpatient_schedule(request):
    schedule=Outpatient_schedule.objects.all()
    context={'schedule':schedule}
    
    return render(request,'booking/table.html',context)

inquiries_complaints/views.py
from django.shortcuts import render

# Create your views here.

settings/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
# Create your views here.
from inquiries_complaints.models import inquiries
from.models import settings


def home(request):
    if request.method=='POST':
        name=request.POST['name']
        phone=request.POST['phone']
        message=request.POST['message']
        submit=inquiries(
            username=name,
            phonenumber=phone,
            message=message,
        )
        submit.save()
        messages.success(request, 'Information send successfully')
        return redirect('/')
    informatins=settings.objects.first()
    return render(request,'settings/index.html',
                    {'informatins':informatins})

booking/templates/booking/regiter.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<style>
    .navbar{
        display: none;
    }
</style>
<section class="reg-main  container-fluid mt-3">
    <!-- <div class="container"> -->
    <div class="reg-item  container-fluid">
        <form method="POST">
            {% csrf_token %}
            <h2>حجز اون الاين</h2>
            <label for="clinic" class="form-label name-lable"> *العيادات</label>
            <select style="display: flex;width: 100%;text-align:center;
                padding: 5px; font-size: 18px;" name="clinic" id="clinics">
                {% for clinic in all_clinics %}
                <option value="{{ clinic.pk }}">{{ clinic }}</option>
                {% endfor %}
            </select>

            <div class="mb-3 mt-3">
                <label for="name" class="form-label"> * الاسم</label>
                <input type="name" class="form-control" id="email" placeholder="ادخل الاسم" name="name" required>
            </div>
            <div class="mb-3 mt-3">
                <label for="phone" class="form-label"> *الهاتف</label>
                <input type="phone" maxlength="11" class="form-control" id="email" placeholder="ادخل الهاتف"
                    name="phone" required>
            </div>
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">الايميل</label>
                <input type="email" class="form-control" id="email" placeholder="ادخل الايميل" name="email">
            </div>
            <div class="mb-3 mt-3">
                <label for="comment" class="form-label">الوصف</label>
                <textarea class="form-control" rows="5" id="comment" name="message"></textarea>
            </div>
            <h3>استعراض المواعيد</h3>
            <div class="mb-3 mt-3 group-buton">
                <button type="reset" class="btn btn-1 btn-Gainsboro">الغاء</button>
                <button type="submit" class="btn btn-primary  btn-2">ارسال</button>
            </div>
            <div class="mb-3 mt-3">
                <button type="submit" class="btn  btn-3"> <a href="{% url 'booking:outpatient_schedule' %}">برجاء الضغط
                        هنا للحصول على جدول
                        العيادات الخارجية</a></button>
            </div>
        </form>
    </div><!--reg-item-->
    <!-- </div>container -->
</section>
{% endblock body %}

booking/templates/booking/table.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<style>
    .navbar{
        display: none;
    }
</style>
<div class="container mt-3 table-page">
    <h2 class="tabele-title">مستشفى جامعة بنى سويف</h2>
    <h3 class="table-head">جدول العيادات الخارجية</h3>
    <div class="table-responsive-sm">
        <table class="table table-striped table-clinic bg.info">
            <thead>
                <tr>
                    <th>ايام العمل </th>
                    <th>عيادات المبنى القديم</th>
                    <th>الادوار</th>
                </tr>
            </thead>
            <tbody>
                {% for schedul in schedule %}
                <tr>
                    <td>
                        {% for workday in schedul.workdays.all %}
                        {{ workday.name }}
                        {% endfor %}
                    </td>
                    <td>{{schedul.clinics}}</td>
                    <td>{{schedul.floor}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock body %}

settings/templates/settings/index.html
{% extends 'base.html' %} {% load static %} {% block body %}

<!---------------------Section-Main-------------------->
{% if messages %} {% for message in messages %} {% if message.tags == 'error' %}
<div class="alert alert-danger" style="text-align: center; font-size: 20px" role="alert">
    {{ message }}
</div>
{% elif message.tags == 'success' %}
<div class="alert alert-success" style="text-align: center; font-size: 20px" role="alert">
    {{ message }}
</div>
{% endif %} {% endfor %} {% endif %}
<section class="main container" id="main-section">
    <div class="main-buttom">
        <button class="main-buttom-item">
            <a href="{% url 'booking:BookingOnline' %}">حجز اون لاين</a>
        </button>
    </div>
    <!--main-buttom-->
    <!-- Carousel -->
    <div id="demo" class="carousel slide" data-bs-ride="carousel">
        <!-- Indicators/dots -->
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="3"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="4"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="5"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="6"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="7"></button>
        </div>

        <!-- The slideshow/carousel -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'image/PICT-hospital.png' %}" alt="Los Angeles" class="d-block" />
                <div class="carousel-caption">
                    <h2>مستشفى جامعة بنى سويف</h2>
                    <h3>منذ عام 1998</h3>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'image/pic3.png' %}" alt="Chicago" class="d-block" />
                <div class="carousel-caption">
                    <h3></h3>
                    <p></p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'image/pict2.jpg' %}" alt="New York" class="d-block" />
                <div class="carousel-caption">
                    <h3></h3>
                    <p></p>
                </div>
            </div>
            <div class="carousel-item active">
                <img src="{% static 'image/pict4.jpg' %}" alt="Los Angeles" class="d-block" />
            </div>
            <div class="carousel-item active">
                <img src="{% static 'image/picture5.jpg' %}" alt="Los Angeles" class="d-block" />
            </div>
            <div class="carousel-item active">
                <img src="{% static 'image/pic7.jpg' %}" alt="Los Angeles" class="d-block" />
            </div>
            <div class="carousel-item active">
                <img src="{% static 'image/picture6.jpg' %}" alt="Los Angeles" class="d-block" />
            </div>
        </div>

        <!-- Left and right controls/icons -->
        <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
        </button>
    </div>
</section>
<!---Main-->

<!-----Section-Information-->
<div class="container p-5 text-dark text-center infr" id="Section-infro">
    <h2 class="infr-header">نبذة عن المستشفى</h2>
    <span class="infr-line"></span>
    <h3 class="Infr-title">تأسست مستشفى جامعة بنى سويف عام 1998</h3>
    <p class="inf-pra">
        بدا العمل بالعيادات الخارجية في إبريل 1998 وتعمل الآن بكامل طاقتها
        ويتردد
        عليها حوالي 800-1000 مريض يوميا تقدم العيادات الخارجية منذ إبريل 1998
        خدماتها لمرضى محافظه بنى سويف في مختلف التخصصات الباطنة العامة والخاصة (
        القلب , الصدر, الأعصاب, النفسية , المتوطنة ... الخ ) الجراحة العامة
        وجراحه
        العظام والمسالك البولية جراحه العيون والأنف والأذن والحنجرة الأطفال
        وأمراض
        النساء والتوليد هذا بالإضافة للعيادات المتخصصة الأخرى مثل: عيادة أمراض
        الدم
        عيادة علاج الأورام بالادويه الكيماوية
    </p>
</div>
<!--infr-->

<!-------Section-Department----------->

<!-- Carousel -->
<section id="Depart" class="Department-sec">
    <div id="dem" class="carousel slide container" data-bs-ride="carousel">
        <div class="dep-header">
            <h2 class="Dep-title">أقسام المستشفى</h2>
            <span class="Dep-line"></span>
        </div>
        <!--dep-header-->
        <!-- Indicators/dots -->
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#dem" data-bs-slide-to="0" class="active"></button>
            <button type="button" data-bs-target="#dem" data-bs-slide-to="1"></button>
            <button type="button" data-bs-target="#dem" data-bs-slide-to="2"></button>
        </div>

        <!-- The slideshow/carousel -->
        <div class="carousel-inner car-Dep">
            <div class="carousel-item active car-item">
                <img src="{% static 'image/pic3.png' %}" alt="Los Angeles" class="d-block" />
                <div class="carousel-caption car-item-header">
                    <h3>العمليات</h3>
                    <p>
                        تضم مستشفى جامعة بنى سويف غرف للعمليات مجهزة بأحدث
                        الأجهزة والمعدات
                        الطبية
                    </p>
                </div>
            </div>
            <div class="carousel-item car-item">
                <img src="{% static 'image/picture5.jpg' %}" alt="Chicago" class="d-block" />
                <div class="carousel-caption car-item-header">
                    <h3>الطوارئ</h3>
                    <p>يقدم قسم الطوارئ خدمات متكاملة علي مدار الساعة</p>
                </div>
            </div>
            <div class="carousel-item car-item">
                <img src="{% static 'image/pict4.jpg' %}" alt="New York" class="d-block" />
                <div class="carousel-caption car-item-header">
                    <h3>الطوارئ</h3>
                    <p>يقدم قسم الطوارئ خدمات متكاملة علي مدار الساعة</p>
                </div>
            </div>
        </div>

        <!-- Left and right controls/icons -->
        <button class="carousel-control-prev Dep-but" type="button" data-bs-target="#dem" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </button>
        <button class="carousel-control-next Dep-but" type="button" data-bs-target="#dem" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
        </button>
    </div>
</section>

<!--------Section-Location---------------->

<div class="container location" id="Connect">
    <h2 class="Loc-header">مستشفى جامعة بنى سويف</h2>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3488.4775233650485!2d31.
    128694924742806!3d29.032454075448715!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.
    1!3m3!1m2!1s0x145a244cb8897899%3A0x57530670d23156f5!2z2YXYs9iq2LTZgdmJINis2KfZhdi52Ycg2KjZhtmJINiz2YjZitmB!5e0!3m2!1sar!
    2seg!4v1682458815270!5m2!1sar!2seg" width="600" height="450" style="border: 0" allowfullscreen loading="lazy"
        referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

<!-------------Connect-section------------>
<section id="connect-us">
    <div class="container connect">
        <div class="connect-rigth">
            <div class="rigth-cont">
                <h4>تابعنا علي</h4>
                <a target="_blank" href="{{informatins.tw_url}}"><i class="fab fa-twitter con-icon1"></i></a>
                <a target="_blank" href="{{informatins.fb_url}}"><i class="fab fa-facebook con-icon2"></i></a>
                
                
            </div>
            <div class="rigth-cont">
                <h4>العنوان</h4>
                <p>{{informatins.adress}}</p>
            </div>

            <div class="rigth-cont">
                <h4>تواصل معنا</h4>
                <p>{{informatins.phoennumbers}}</p>
            </div>
        </div>
        <!--connect rigth-->

        <div class="connect-left">
            <h4>للاستفسار والشكاوي</h4>
            <span class="left-line"></span>
            <form method="POST">
                {% csrf_token %}
                <input name="name" required type="text" placeholder="الاسم" />
                <input name="phone" required type="number" placeholder="رقم الهاتف" />
                <textarea name="message" required id placeholder="الرسالة" cols="30" rows="10"></textarea>
                <button type="submit" value="ارسال" class="Con-btn">ارسال</button>
            </form>
        </div>
        <!--connect-left-->
    </div>
    <!--connent-->
</section>

{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hospital</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link href="{% static 'CSS/all.css' %}" rel="stylesheet">
    <link href="{% static 'CSS/style.css' %}" rel="stylesheet">
</head>

<body>
    <!--Section-Header-->
    <nav class="navbar navbar-expand-sm header-section">
        <div class="container header-section-item">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button><!--button-navbar-toggler-->
            <div class="collapse navbar-collapse nav-list nav-list-header" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">تواصل معنا</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="'/">اقسام المستشفى</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./">نبذة عن المستشفى</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/">الرئيسة</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right logo-image" style="visibility: hidden;">
                    <li>
                        <a href="#"><img alt="Forestpin logo" src="{{ informatins.logo.url }}" id="logofpin"></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right logo-image">
                    <li>
                        <a href="#"><img alt="Forestpin logo" src="{{ informatins.logo.url }}" id="logofpin"></a>
                    </li>
                </ul>
            </div><!--nav-list-header-->

        </div><!--header-section-item-->
    </nav><!--navbar-->
    {% block body %}
        
    {% endblock body %}
    <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>